/**
 * The rest of the world (Phase 2 World Population). Real content.
 * Frontal · Parietal · Occipital · Temporal (cognitive evolution) · Stem ·
 * Projects · Research. Terse authoring — tier drives importance, fallback auto.
 */
export const mindRaw = [
  // ======================= FRONTAL — Goals / Vision =======================
  { id: "future-vision", kind: "goal", title: "Future Vision", subtitle: "Where this is all going", region: "frontal", tier: "major", tags: ["vision"], connections: ["chanakya", "founder", "ai-systems-architect", "obsession-ai-os"], status: "concept", content: "Building systems that think — a life spent at the frontier of intelligence." },
  { id: "mtech", kind: "goal", title: "MTech", subtitle: "Deepen the foundations", region: "frontal", tier: "major", tags: ["vision", "education"], connections: ["research-engineer", "math", "machine-learning"], status: "wip", content: "A master's sharpening the theoretical edge in ML and systems." },
  { id: "research-engineer", kind: "goal", title: "Research Engineer", subtitle: "Build at the frontier", region: "frontal", tier: "major", tags: ["vision", "career"], connections: ["pytorch", "mtech", "the-research-gap"], status: "wip", content: "Translate research into systems that ship." },
  { id: "ai-systems-architect", kind: "goal", title: "AI Systems Architect", subtitle: "Design intelligence at scale", region: "frontal", tier: "major", tags: ["vision", "systems"], connections: ["system-design", "chanakya-os", "future-vision"], status: "concept", content: "Architect large-scale AI systems — reliable, observable, humane." },
  { id: "founder", kind: "goal", title: "Founder", subtitle: "Ship a company", region: "frontal", tier: "legendary", tags: ["vision", "entrepreneurship"], connections: ["chanakya", "ai-systems-architect", "future-vision"], status: "concept", content: "Found a studio that turns frontier AI into products people love." },

  // ==================== PARIETAL — Logic / Reasoning ======================
  { id: "data-structures", kind: "skill", title: "Data Structures", region: "parietal", tier: "major", tags: ["logic", "cs"], connections: ["algorithms", "database-design"], status: "live", content: "The shapes information takes — and why the right one changes everything." },
  { id: "algorithms", kind: "skill", title: "Algorithms", region: "parietal", tier: "major", tags: ["logic", "cs"], connections: ["data-structures", "competitive-programming", "optimization"], status: "live", content: "Efficient thought — complexity, correctness, trade-offs." },
  { id: "competitive-programming", kind: "skill", title: "Competitive Programming", region: "parietal", tier: "standard", tags: ["logic"], connections: ["algorithms"], status: "live", content: "Sharpening problem-solving under pressure." },
  { id: "optimization", kind: "skill", title: "Optimization", region: "parietal", tier: "standard", tags: ["logic", "math"], connections: ["algorithms", "machine-learning"], status: "live", content: "Finding the best within constraints." },
  { id: "logical-reasoning", kind: "skill", title: "Logical Reasoning", region: "parietal", tier: "standard", tags: ["logic"], connections: ["problem-decomposition"], status: "live", content: "Rigorous, step-by-step thinking." },
  { id: "problem-decomposition", kind: "skill", title: "Problem Decomposition", region: "parietal", tier: "standard", tags: ["logic"], connections: ["logical-reasoning", "system-design"], status: "live", content: "Breaking the impossible into the doable." },
  { id: "software-architecture", kind: "skill", title: "Software Architecture", region: "parietal", tier: "major", tags: ["logic", "systems"], connections: ["distributed-systems", "system-design"], status: "live", content: "Structuring software for change and scale." },
  { id: "distributed-systems", kind: "skill", title: "Distributed Systems", region: "parietal", tier: "major", tags: ["logic", "systems"], connections: ["software-architecture", "networking", "event-bus"], status: "live", content: "Reasoning about systems with no single source of truth." },

  // ==================== OCCIPITAL — Visual / Research =====================
  { id: "visual-thinking", kind: "research", title: "Visual Thinking", region: "occipital", tier: "major", tags: ["visual", "cognition"], connections: ["architecture-diagrams", "system-maps", "neural-interfaces"], status: "live", content: "Thinking in pictures — turning abstraction into visual structure." },
  { id: "architecture-diagrams", kind: "project", title: "Architecture Diagrams", region: "occipital", tier: "standard", tags: ["visual"], connections: ["visual-thinking", "system-maps"], status: "live", content: "Rendering systems as diagrams — clarity as a thinking tool." },
  { id: "system-maps", kind: "project", title: "System Maps", region: "occipital", tier: "standard", tags: ["visual", "systems"], connections: ["architecture-diagrams", "system-design"], status: "live", content: "Mapping how the pieces of a system relate." },
  { id: "neural-interfaces", kind: "project", title: "Neural Interfaces", region: "occipital", tier: "major", tags: ["visual", "webgl"], connections: ["threejs", "interactive-systems", "inside-the-mind"], status: "wip", content: "Interfaces you fly through — like the one you're inside right now." },
  { id: "data-visualization", kind: "skill", title: "Data Visualization", region: "occipital", tier: "standard", tags: ["visual", "data"], connections: ["knowledge-graphs", "knowledge-graph-explorer"], status: "live", content: "Making data legible and explorable." },
  { id: "ai-workflows", kind: "research", title: "AI Workflows", region: "occipital", tier: "standard", tags: ["visual", "ai"], connections: ["agentic-ai", "agent-architectures"], status: "live", content: "Designing how humans and agents collaborate visually." },
  { id: "knowledge-graphs", kind: "skill", title: "Knowledge Graphs", region: "occipital", tier: "major", tags: ["visual", "knowledge"], connections: ["rag", "knowledge-layer", "knowledge-graph-explorer", "research-agentic"], status: "live", content: "Relationships as first-class data — the substrate of understanding." },
  { id: "agent-architectures", kind: "research", title: "Agent Architectures", region: "occipital", tier: "standard", tags: ["visual", "agents"], connections: ["agentic-ai", "agent-runtime"], status: "live", content: "How agents are structured to plan and act." },
  { id: "interactive-systems", kind: "project", title: "Interactive Systems", region: "occipital", tier: "standard", tags: ["visual", "ui"], connections: ["neural-interfaces", "react"], status: "live", content: "Systems that respond and feel alive." },

  // ============ TEMPORAL — Cognitive Evolution Archive ====================
  { id: "curiosity-engine", kind: "memory", title: "Curiosity Engine", cluster: "Identity Formation", region: "temporal", tier: "major", tags: ["identity"], connections: ["builder-mindset", "python"], content: "The drive to understand how things work rather than simply use them." },
  { id: "builder-mindset", kind: "memory", title: "Builder Mindset", cluster: "Identity Formation", region: "temporal", tier: "major", tags: ["identity"], connections: ["curiosity-engine", "systems-thinking"], content: "The transition from consuming technology to creating it." },
  { id: "systems-thinking", kind: "memory", title: "Systems Thinking", cluster: "Identity Formation", region: "temporal", tier: "major", tags: ["identity"], connections: ["builder-mindset", "system-design", "from-models-to-systems"], content: "The realization that complex outcomes emerge from connected components." },
  { id: "mem-discovering-linux", kind: "memory", title: "Discovering Linux", cluster: "Learning Transformations", region: "temporal", tier: "major", tags: ["journey"], connections: ["linux", "operating-systems"], content: "Where software stopped being magic and became something I could open up." },
  { id: "mem-falling-into-ai", kind: "memory", title: "Falling Into AI", cluster: "Learning Transformations", region: "temporal", tier: "legendary", tags: ["journey", "ai"], connections: ["machine-learning", "deep-learning", "understanding-intelligence"], content: "Watching a model improve on its own — the moment everything changed direction." },
  { id: "understanding-intelligence", kind: "memory", title: "Understanding Intelligence", cluster: "Learning Transformations", region: "temporal", tier: "major", tags: ["journey", "ai"], connections: ["agentic-ai", "research-reasoning", "mem-falling-into-ai"], content: "Beginning to ask not just how to build AI, but what intelligence is." },
  { id: "learning-through-failure", kind: "memory", title: "Learning Through Failure", cluster: "Challenges", region: "temporal", tier: "major", tags: ["challenge"], connections: ["complexity-wall"], content: "Failed experiments that led to deeper understanding." },
  { id: "complexity-wall", kind: "memory", title: "Complexity Wall", cluster: "Challenges", region: "temporal", tier: "major", tags: ["challenge"], connections: ["learning-through-failure", "system-design"], content: "The point where simple coding became systems engineering." },
  { id: "the-research-gap", kind: "memory", title: "The Research Gap", cluster: "Challenges", region: "temporal", tier: "major", tags: ["challenge"], connections: ["research-engineer", "complexity-wall"], content: "Realizing the difference between tutorials and original thinking." },
  { id: "obsession-agentic", kind: "memory", title: "Agentic Systems", cluster: "Obsessions", region: "temporal", tier: "major", tags: ["obsession", "agents"], connections: ["agentic-ai", "agent-runtime"], content: "The conviction that software should act, not just respond." },
  { id: "obsession-ai-os", kind: "memory", title: "AI Operating Systems", cluster: "Obsessions", region: "temporal", tier: "legendary", tags: ["obsession", "vision"], connections: ["research-ai-os", "chanakya-os", "future-vision"], content: "The idea that won't let go — an OS where intelligence is the substrate." },
  { id: "obsession-knowledge-networks", kind: "memory", title: "Human Knowledge Networks", cluster: "Obsessions", region: "temporal", tier: "major", tags: ["obsession", "knowledge"], connections: ["knowledge-graphs", "knowledge-layer"], content: "A fascination with how knowledge connects across minds." },
  { id: "mem-starting-chanakya", kind: "memory", title: "Starting Chanakya", cluster: "Turning Points", region: "temporal", tier: "legendary", tags: ["turning-point", "chanakya"], connections: ["chanakya", "chanakya-os", "from-models-to-systems"], content: "The day Chanakya went from a sketch to a system — the seed of everything here. Probably the most important memory in this entire world." },
  { id: "thinking-beyond-apps", kind: "memory", title: "Thinking Beyond Apps", cluster: "Turning Points", region: "temporal", tier: "major", tags: ["turning-point"], connections: ["systems-thinking", "ai-systems-architect"], content: "Moving from building products to designing intelligent systems." },
  { id: "from-models-to-systems", kind: "memory", title: "From Models To Systems", cluster: "Turning Points", region: "temporal", tier: "legendary", tags: ["turning-point"], connections: ["machine-learning", "agentic-ai", "chanakya", "system-design"], content: "The shift from training models to architecting whole minds." },

  // ======================= STEM — Foundations =============================
  { id: "math", kind: "skill", title: "Mathematics", region: "stem", tier: "major", tags: ["fundamentals", "math"], connections: ["linear-algebra", "probability", "calculus", "machine-learning"], status: "live", content: "The language deep learning is written in." },
  { id: "linear-algebra", kind: "skill", title: "Linear Algebra", region: "stem", tier: "standard", tags: ["fundamentals", "math"], connections: ["math", "deep-learning"], status: "live", content: "Vectors, matrices and transformations." },
  { id: "probability", kind: "skill", title: "Probability", region: "stem", tier: "standard", tags: ["fundamentals", "math"], connections: ["statistics", "math"], status: "live", content: "Reasoning under uncertainty." },
  { id: "statistics", kind: "skill", title: "Statistics", region: "stem", tier: "standard", tags: ["fundamentals", "math"], connections: ["probability", "product-pricing-model"], status: "live", content: "Inference from data." },
  { id: "calculus", kind: "skill", title: "Calculus", region: "stem", tier: "standard", tags: ["fundamentals", "math"], connections: ["math", "optimization"], status: "live", content: "Gradients and change — how models learn." },
  { id: "operating-systems", kind: "skill", title: "Operating Systems", region: "stem", tier: "major", tags: ["fundamentals", "cs"], connections: ["computer-networks", "linux", "c"], status: "live", content: "Processes, memory, scheduling — the substrate everything stands on." },
  { id: "computer-networks", kind: "skill", title: "Computer Networks", region: "stem", tier: "standard", tags: ["fundamentals", "cs"], connections: ["operating-systems", "networking"], status: "live", content: "Packets, protocols and latency — the physics of distributed systems." },
  { id: "databases", kind: "skill", title: "Databases", region: "stem", tier: "major", tags: ["fundamentals", "data"], connections: ["postgresql", "mongodb", "database-design"], status: "live", content: "Modelling, indexing and querying durable state." },
  { id: "oop", kind: "skill", title: "Object-Oriented Programming", region: "stem", tier: "standard", tags: ["fundamentals"], connections: ["java", "software-engineering"], status: "live", content: "Modelling the world as interacting objects." },
  { id: "software-engineering", kind: "skill", title: "Software Engineering", region: "stem", tier: "standard", tags: ["fundamentals"], connections: ["oop", "software-architecture"], status: "live", content: "The discipline of building software that lasts." },
  { id: "cryptography", kind: "skill", title: "Cryptography", region: "stem", tier: "minor", tags: ["fundamentals", "security"], connections: ["computer-networks"], status: "live", content: "Trust and secrets in adversarial systems." },
  { id: "numerical-methods", kind: "skill", title: "Numerical Methods", region: "stem", tier: "minor", tags: ["fundamentals", "math"], connections: ["calculus", "machine-learning"], status: "live", content: "Computing with continuous math, approximately." },

  // ====================== PROJECTS — Flagship =============================
  { id: "chanakya-os", kind: "project", title: "Chanakya OS", subtitle: "An operating system for agents", region: "projects", tier: "legendary", tags: ["flagship", "agents", "os"], connections: ["chanakya", "agentic-ai", "knowledge-graphs", "rag", "system-design", "python", "obsession-ai-os"], status: "wip", content: "The flagship: an OS where agents, memory and knowledge compose into a thinking system. Everything else here feeds into it." },
  { id: "isl-recognition", kind: "project", title: "ISL Recognition", subtitle: "CNN-Transformer for sign language", region: "projects", tier: "major", tags: ["flagship", "cv", "dl"], connections: ["computer-vision", "deep-learning", "python", "fastapi", "docker"], status: "live", content: "A CNN-Transformer recognising Indian Sign Language — productionised end to end with an MLOps pipeline." },
  { id: "product-pricing-model", kind: "project", title: "Product Pricing Model", subtitle: "ML for optimal pricing", region: "projects", tier: "major", tags: ["flagship", "ml"], connections: ["machine-learning", "python", "statistics", "optimization"], status: "live", content: "A regression + feature-engineering pipeline for data-driven pricing." },
  { id: "knowledge-graph-explorer", kind: "project", title: "Knowledge Graph Explorer", subtitle: "Search a graph visually", region: "projects", tier: "major", tags: ["flagship", "viz"], connections: ["knowledge-graphs", "data-visualization", "threejs"], status: "wip", content: "An interactive explorer for large knowledge graphs — search, traverse, understand." },
  { id: "inside-the-mind", kind: "project", title: "Inside The Mind", subtitle: "This very experience", region: "projects", tier: "major", tags: ["flagship", "webgl"], connections: ["neural-interfaces", "threejs", "react"], status: "wip", content: "An explorable digital consciousness — the project you are inside of." },

  // ====================== RESEARCH — Frontier =============================
  { id: "research-agentic", kind: "research", title: "Agentic AI", subtitle: "Software that acts", region: "research", tier: "major", tags: ["research", "agents"], connections: ["agentic-ai", "research-multi-agent", "research-autonomous"], status: "wip", content: "Open questions in planning, tool use and reliability of agents." },
  { id: "research-multi-agent", kind: "research", title: "Multi-Agent Systems", region: "research", tier: "major", tags: ["research", "agents"], connections: ["research-agentic", "agent-runtime"], status: "wip", content: "Coordination, negotiation and emergence among many agents." },
  { id: "long-term-memory", kind: "research", title: "Long-Term Memory", region: "research", tier: "major", tags: ["research", "memory"], connections: ["memory-layer", "vector-databases", "research-rag"], status: "wip", content: "How systems remember, forget and recall across long horizons." },
  { id: "research-rag", kind: "research", title: "RAG", subtitle: "Retrieval-augmented generation", region: "research", tier: "standard", tags: ["research", "rag"], connections: ["rag", "vector-databases", "knowledge-graphs"], status: "wip", content: "Grounding generation in retrieved knowledge." },
  { id: "research-deep-learning", kind: "research", title: "Deep Learning", region: "research", tier: "standard", tags: ["research", "dl"], connections: ["deep-learning", "research-transformers"], status: "wip", content: "Frontier questions in representation and training." },
  { id: "research-transformers", kind: "research", title: "Transformers", region: "research", tier: "standard", tags: ["research", "nlp"], connections: ["transformers", "research-deep-learning"], status: "wip", content: "Attention, scaling and what comes after." },
  { id: "research-cv", kind: "research", title: "Computer Vision", region: "research", tier: "standard", tags: ["research", "cv"], connections: ["computer-vision", "research-federated"], status: "wip", content: "Perception, recognition and visual reasoning." },
  { id: "research-federated", kind: "research", title: "Federated Learning", region: "research", tier: "standard", tags: ["research", "privacy"], connections: ["machine-learning", "research-cv"], status: "concept", content: "Learning across devices without centralising data." },
  { id: "research-ai-os", kind: "research", title: "AI Operating Systems", region: "research", tier: "legendary", tags: ["research", "vision"], connections: ["chanakya-os", "obsession-ai-os", "research-agentic"], status: "concept", content: "The research thesis behind Chanakya — intelligence as an operating substrate." },
  { id: "research-human-ai", kind: "research", title: "Human-AI Collaboration", region: "research", tier: "standard", tags: ["research", "hci"], connections: ["ai-workflows", "research-reasoning"], status: "concept", content: "Interfaces and protocols for humans and AI to think together." },
  { id: "research-reasoning", kind: "research", title: "Reasoning Systems", region: "research", tier: "major", tags: ["research", "reasoning"], connections: ["agentic-ai", "research-human-ai", "understanding-intelligence"], status: "wip", content: "Making machine reasoning reliable and inspectable." },
  { id: "research-autonomous", kind: "research", title: "Autonomous Agents", region: "research", tier: "standard", tags: ["research", "agents"], connections: ["research-agentic", "agent-runtime"], status: "wip", content: "Agents that pursue goals with minimal supervision." },
  { id: "vector-databases", kind: "research", title: "Vector Databases", region: "research", tier: "standard", tags: ["research", "data"], connections: ["research-rag", "long-term-memory", "databases"], status: "live", content: "Similarity search at scale — memory for AI systems." },
];
